### PR TITLE
Optional skip for package update (only for apt currently)

### PR DESCRIPTION
**Pull request by dimon222**
Basically #18. Only added support for apt.
Might require some testing from @ThomDietrich

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @dimon222, I've tested both options and they seem to work great! Thanks for that 👍 

I'm not sure if "skipupdate" is a clearly understandable. Maybe you could add a better description. I also thing "-SUPD" is highly unusual. Short parameters are almost always single letters. In special cases like this it'S also common to only provide a long parameter name. How about `-s` or `-su` and `skiprepoupdate`? Best!

**Comment by dimon222** [comment]
Yeah, I thought same about naming, but didn't find better option.
`-s` is already used by saveupdates due to its case insensitive behavior:
image

`-su` would be confusing since people already expect `su` to be superuser related.   
I'm good with long name as `-skiprepoupdate` but still think there might be better name for short alias.

**Comment by ThomDietrich** [comment]
Still think it's unusual but okay, `-sru` would be fine with me.

In the usage printout you used "-SRU", are you going to replace it?
How about "Skip update for package list" -> "Skip the repository package update during update count calculation (apt only)"

**Comment by dimon222** [comment]
It's following the same case insensitive pattern, but sure I can make it lowercase `-sru`. Also, I'm good on description update.

**Comment by ThomDietrich** [comment]
Wonderful. Then there is one last detail. My request originated out of the idea to issue the update right after an apt action. I believe you can add your new parameter to the README part regarding `DPkg::Post-Invoke`.

**Comment by dimon222** [comment]
Should be done. I will run couple of tests later today to confirm that everything is ok.

**Pull request merged**
