### PR TITLE
Small changes and better cli handling

### PR DESCRIPTION
**Pull request by tavinus**
- Added some extra options:
```
Options:
  -h | --help        Shows this help and exits
  -v | --verbose     Verbose mode (shows messages)
  -V | --version     Shows version information and exits
  -t | --theme       Shows Motd info on screen, based on the chosen theme
  -C | --colortest   Prints color test to screen
  -U | --updates     Checks updates and prints to stdout
  -s | --saveupdates Check updates and saves to disk
                     (same as /usr/local/bin/FireMotD -U > /var/tmp/updatecount.txt)
```

- Created Makefile for easier system install.
- Updated readme.md (broken links and extra info).
- Created bash_completion.d/FireMotD Bash auto completion file.
- Some extra parameter validation added.
- Options --updates and --saveupdates now check if running under root UID (maybe this is needed only in Debian? need to check that).
- Corrected --colortest to reset the color to white after running (everything was blue after that).

### CODE REVIEW

**Comment by willemdh** [comment]
Wow, thank you Tavinus. You are actually the first person to submit a pr for my FireMotD project! I'll have a look at what you scripted asap!

**Comment by willemdh** [comment]
@tavinus How are you installing FireMotD with this makefile?

**Comment by tavinus** [comment]
Ops.. sorry for the delay.

The makefile is kind of optional, but I like having that option.

Just `sudo make install` will install the script to `/usr/local/bin/FireMotD` (and set exec permissions). One can change the variable `IDIR=/usr/local/bin` on the makefile to install somewhere else. I was using /usr/local/sbin but that is not on the default $PATH on many systems.

Then `sudo make bash_completion`will install the bash completion script to `/etc/bash_completion.d/FireMotD` (Bash completion must be enabled on the system to work). 

Finally: `sudo make uninstall` will remove both the script and bash completion.

I understand that some people will not want this system-wide available. But some will, so its there.

I have added the makefile and cron information to the readme.md file.

Glad to be of some help. Thanks for the script!

Cheers!
Gus (Tavinus)

**Comment by tavinus** [comment]
Man.... not too sure why but I was trying to rebase to upstream (yours) and got lots of conflicts. After some research I was able to reset it to yours. It is probably a good idea to use the dev branch to make pull requests. Cheers!

**Pull request merged**
